### ISSUE TITLE
"include original headers" ?

### ISSUE THREAD

**Issue by wrabit** [spatie/laravel-mailcoach-ses-feedback#17]
When setting up the notification SNS, do we need to check these?

![image](https://user-images.githubusercontent.com/5918271/102986685-1e482980-4509-11eb-9337-0f63d9b71a5c.png)

**Comment by riasvdv** [comment]
Where are you seeing these configuration options? Are these new? I'm not seeing them in our SNS or SES configurations

**Comment by wrabit** [comment]
Not new, but I was accessing them via the SES screen on AWS. After choosing your domain, you have a Notifications panel. 

I've since approached it from the docs-recommended way, but still curious to know what I should select here, or if this is still relevant coming at it the other way.

**Comment by riasvdv** [comment]
Ah, we don't have them checked in our configuration, I haven't opened that screen before today, so they're not needed.
