### ISSUE TITLE
SNS Event types

### ISSUE THREAD

**Issue by wrabit** [spatie/laravel-mailcoach-ses-feedback#18]
In package mode, which event types should we select?

The graphic in docs has only Reject Bounce and Complaint. Are Clicks and Opens ok to leave off?

From the docs "Add a SNS destination in the Event Destinations and make sure to check the event types **you would like to receive**" is a bit open ended, some opinion here about what we _should_ be selecting (in order to have all features and stats recorded) would be re-assuring thus making setting up smoother.

**Comment by riasvdv** [comment]
If you want opens & clicks to be tracked, you check those as well. The wording could be a bit better, if you want you can send a PR to the docs repo for this. Otherwise we'll update it soon

**Comment by wrabit** [comment]
I notice it modifies links to point to a different endpoint on your server so was not sure if clicks and opens were tracked by other means.

**Comment by riasvdv** [comment]
Clicks and opens are always tracked by the provider (SES, Mailgun, Sendgrid..), they then send a webhook to us. So if you disable it on the provider's end we won't get any webhooks so we won't track any clicks or opens
