### ISSUE TITLE
Failed on sentTestEmail Campaign

### ISSUE THREAD

**Issue by leonardliau27** [spatie/laravel-mailcoach-ses-feedback#21]
Hi,

I setup the mailcoach and setting Mail Configuration. I test send email there and it was working fine, i receive the email testing.
The problem occured when i test send email in campaign. I create campaign and not receive email. I check in horizon monitoring, the error was onn SendTestMailJob
![image](https://user-images.githubusercontent.com/80967495/111796618-ec254880-88fa-11eb-9694-26e3490266fc.png)

Can anybody got this problem. Please help. Thank you

**Comment by freekmurze** [comment]
Have you tried to restart Horizon (or maybe your entire server)?

**Comment by leonardliau27** [comment]
yes. already restart the Horizon. still got the error.. Failed send

**Comment by leonardliau27** [comment]
Are there must setting the mailer different between testing in Mail Configuration and for campaign?
Somehow i got this smtp error, but actually i set using ses driver in Mail configuration
![image](https://user-images.githubusercontent.com/80967495/111800197-4f64aa00-88fe-11eb-9f45-67e478395e48.png)
