### ISSUE TITLE
Significant variation between recorded feedback and AWS console

### ISSUE THREAD

**Issue by adamthehutt** [spatie/laravel-mailcoach-ses-feedback#22]
Amazon SES provides a "reputation dashboard" in the console that shows a snapshot of your current bounce rate and complaint rate over the past X sends.

The metrics they provide are frustratingly vague, but they are nonetheless very different from what Mailcoach has captured in the database. For example, the reputation dashboard says that my complaint rate over the past ~12,378 email is 0.12%, which would mean 15 complaints. However, the mailcoach_send_feedback_items table only includes 2 records with the type "complaint" over that span. 

Can anyone suggest a reason for this divergence? Is there any reason that some but not all complaints would be captured by Mailcoach?

Also:
- I don't have any unprocessed webhooks
- I'm using Flare for error tracking and there have been no errors / exceptions recorded in connection with the webhook endpoint

**Comment by riasvdv** [comment]
Is there a way for you to see which exact complaints you've had in SES? Maybe you could find the cause of the missing ones through that?

**Comment by adamthehutt** [comment]
@riasvdv Thanks to Cloudwatch, I now have two examples of "complaints" that were not recorded by Mailcoach.

Here's the really weird part... I'm logging the "mailcoach-send-uuid" header as part of the Cloudwatch metric. For these two specific ones, the UUID doesn't match anything in the mailcoach_sends table. 

To be clear, there are several other examples where the mailcoach-send-uuid captured does correspond to a mailcoach_sends record.

Where would I even begin to look for what these UUIDs represent?

**Comment by riasvdv** [comment]
Are you sending welcome emails when a user subscribes? They might be sent through the same AWS account and bouncing there.

**Comment by adamthehutt** [comment]
@riasvdv No, that's not it. The issue is that when you delete a subscriber the foreign key settings cascade to the sends table. Then when the webhook is processed, the UUID doesn't match anything in the sends table, so the feedback is ignored. The simple answer seems to be to never delete records from the subscribers table (or perhaps to soft delete them instead).

**Comment by riasvdv** [comment]
Or we could delete the webhook if we find there's no send, I think we do that in another feedback package as well
