### ISSUE TITLE
Why handle only first webhook call for every email?

### ISSUE THREAD

**Issue by Gaia-Nutrition** [spatie/laravel-mailcoach-ses-feedback#8]
When a webhook call is processed, the `ProcessSesWebhookJob` checks, whether or not the call being handled is the first for this email. If not, it stops handling the call and deletes it. https://github.com/spatie/laravel-mailcoach-ses-feedback/blob/666b58e890ecfd4aae2d1e02543ce19485d9e541/src/ProcessSesWebhookJob.php#L33-L37

Why is that? If there are multiple events (maybe an open and a link click), would the click not be processed in that case? Also, why is the webhook call not deleted once processed successfully?

**Comment by freekmurze** [comment]
I'm thinking that every webhook sent by SES gets its own message id. Sometimes messages will come in twice. This method will avoid handling the same message twice.

If another event for the same mail comes in it will have a different message id

Right @riasvdv ?

**Comment by Gaia-Nutrition** [comment]
To me it seems that the `messageId` field of SES feedback calls corresponds to an SES assigned id for the email (see [SES Event Records Contents](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/event-publishing-retrieving-sns-contents.html#event-publishing-retrieving-sns-contents-mail-object))

Also, this is the same ID you are using to find the `Send` model from the database. There you call it `transport_message_id`

**Comment by freekmurze** [comment]
@riasvdv Could you take a look at this one in the next couple of days?

**Comment by riasvdv** [comment]
The SES messageId is indead a messageId assigned by AWS, this is because AWS guarantees that your webhook is called **at least once**, which can mean that it can be called more than once, and we should account for that.

So if we already have a webhook with that ID, we don't want to store and process it again, because it's a duplicate from AWS.

**Comment by Gaia-Nutrition** [comment]
Ah, found what was going on here. Posting this for anyone also getting confused here:
This is (roughly) how the webhook payload looks like:
```json
{
  "Type": "Notification",
  "MessageId": "757f9384-[...]",
  "TopicArn": "arn:aws:sns:eu-central-1:[...]",
  "Subject": "Amazon SES Email Event Notification",
  "Message": {
    "eventType": "Open",
    "mail": {
      "messageId": "01070171a65b8112-[...]",
      [...]
    },
    "open": {
      "timestamp": "2020-04-23T09:26:15.036Z",
      [...]
    }
  },
  [...]
}
```
So, the actual S**E**S event is sent to the webhook wrapped in a S**N**S notification. So there are two distinct `messageId` fields per webhook call. To avoid confusion, the `isFirstOfThisSesMessage` could be renamed to `isFirstCallForThisEvent` or `isFirstOfThisSnsNotification`
