### ISSUE TITLE
Question - Webhook call  are never deleted ? 

### ISSUE THREAD

**Issue by YannikFirre** [spatie/laravel-mailcoach-ses-feedback#9]
Hello,

I notice that my table 'webhook_calls' remains full, the entries in db are not deleted once processed ? Is there anything planned to clean it or do I have to empty it manually?

Thanks ;)

**Comment by freekmurze** [comment]
Currently they are never deleted, feel free to delete them after a week or so.

In the next major release, Mailcoach will take care of this automatically.
